version: '2'

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      # Export port to host
      - "8080:8080"
    environment:
      # Environment variables that will be overridden when start
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:10.5'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres